"""
Generate the web application's static data files
================================================

    python 06_webapp/build_app_data.py

The application ships four generated files so that it can start on a machine
that has no copy of the dataset - a Hugging Face Space carries the models and
the app, not the corpus. Generating them rather than maintaining them by hand
is the point: the legacy lists had drifted from the data they were supposed to
describe, carrying a misspelt cell line ("chondrocyteyte") and biomaterial
names that no longer matched any dataset column ("laponite" against
"Laponite-XLG (%w/w)"), so a user selecting them was choosing a feature the
model had never seen.

Writes:
    biomaterials.py         BIOMATERIAL_OPTIONS, and observed ranges
    cell_lines.py           CELL_LINE_OPTIONS, and observed density ranges
    model_performance.py    the benchmarked test-set scores shown in the UI
    corpus_reference.*      the observed formulations, for grounding

The last is not a convenience. Two of the measures that constrain the language
model - the nearest published formulations supplied as precedent, and the
statement of whether the candidate lies inside the observed ranges - are
computed against the corpus, so without it the prompt would assert that no
similar formulation exists and that the candidate is in range, neither of which
would have been checked. It carries only the predictor and target columns.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import numpy as np
import pandas as pd

from mlate import config as cfg
from mlate import style as ms
from mlate.dataset import load_dataset

HERE = Path(__file__).resolve().parent
ML_TABLES = cfg.step_dir("04_machine_learning", "tables")
DL_TABLES = cfg.step_dir("05_deep_learning", "tables")

# The application serves prediction inside the design space the corpus covers,
# which is the interpolation regime the random protocol estimates. Study-grouped
# scores are the conservative bound for a genuinely new laboratory and are
# reported in the manuscript; they describe a harder task than the one a user of
# the tool is performing.
PROTOCOL = "random"
TOP_N = 12


def _header(title: str) -> str:
    return (f'"""\n{title}\n\nGENERATED by 06_webapp/build_app_data.py - do not '
            f'edit by hand.\nRegenerate after any change to the dataset or the '
            f'benchmark tables.\n"""\n\n')


def build_biomaterials(df, columns) -> None:
    """Material names exactly as the model's feature columns spell them."""
    mats = list(columns.biomaterials)
    ranges = {}
    for m in mats:
        v = pd.to_numeric(df[m], errors="coerce")
        v = v[v > 0]
        if len(v) == 0:
            continue
        ranges[m] = {"min": float(v.min()), "max": float(v.max()),
                     "median": float(v.median()), "n": int(len(v))}

    body = _header("Biomaterial vocabulary and observed concentration ranges.")
    body += "BIOMATERIAL_OPTIONS = [\n"
    body += "".join(f'    {m!r},\n' for m in mats)
    body += "]\n\n"
    body += ("# Observed range among formulations that CONTAIN each material.\n"
             "# The UI seeds its range widgets from these so a user starts\n"
             "# inside the region the models were trained on; values outside\n"
             "# are permitted but flagged as extrapolation.\n")
    body += f"BIOMATERIAL_RANGES = {json.dumps(ranges, indent=4)}\n"
    (HERE / "biomaterials.py").write_text(body, encoding="utf-8")
    print(f"  biomaterials.py      {len(mats)} materials, "
          f"{len(ranges)} with observed ranges")


def build_cell_lines(df, columns) -> None:
    counts = df[columns.cell_line].value_counts()
    lines = [cfg.ACELLULAR_TOKEN] + [c for c in counts.index
                                     if c != cfg.ACELLULAR_TOKEN]

    dens = {}
    for line in lines:
        v = pd.to_numeric(df.loc[df[columns.cell_line] == line,
                                 columns.cell_density], errors="coerce")
        v = v[v > 0]
        if len(v):
            dens[line] = {"min": float(v.min()), "max": float(v.max()),
                          "median": float(v.median())}

    body = _header("Cell-line vocabulary and observed seeding densities.")
    body += ("# Ordered by frequency in the corpus, with the acellular token\n"
             "# first because it selects a different mode: cell response is\n"
             "# not applicable and WSSQ falls back to printability alone.\n")
    body += f"ACELLULAR_TOKEN = {cfg.ACELLULAR_TOKEN!r}\n\n"
    body += "CELL_LINE_OPTIONS = [\n"
    body += "".join(f'    {c!r},\n' for c in lines)
    body += "]\n\n"
    body += "CELL_LINE_COUNTS = {\n"
    body += "".join(f'    {c!r}: {int(counts[c])},\n' for c in lines)
    body += "}\n\n"
    body += ("# Density in 10^6 cells/mL, among records using that line.\n")
    body += f"CELL_DENSITY_RANGES = {json.dumps(dens, indent=4)}\n"
    (HERE / "cell_lines.py").write_text(body, encoding="utf-8")
    print(f"  cell_lines.py        {len(lines)} lines "
          f"({len(dens)} with density data)")


def served_pairs() -> set[tuple[str, str]]:
    """
    The (model, task) pairs the application can offer.

    Resolved through the serving layer rather than by listing one directory, so
    the column cannot claim a model is in the menu that the menu does not in
    fact contain. All three families are servable: the conventional
    classifiers, the deep networks, and the in-context foundation models.
    """
    from mlate import serving
    return {(stub.name, task)
            for task in ("printability", "cell_response")
            for stub in serving.discover(cfg.MODEL_DIR, task, PROTOCOL)}


def build_performance() -> None:
    """
    Benchmarked test-set scores for the models the application offers.

    Read from the tuned benchmark rather than transcribed, because the legacy
    table described models that no longer exist and scores that were never
    recomputed after the dataset grew.
    """
    frames = []
    ml = ML_TABLES / "tuned_benchmark.xlsx"
    if ml.exists():
        d = pd.read_excel(ml)
        d = d[d["selection"].isin(["weighted", "composed"])]
        d["family"] = "ML"
        frames.append(d)
    dl = DL_TABLES / "dl_benchmark.xlsx"
    if dl.exists():
        d = pd.read_excel(dl)
        d = d[d["selection"] == "weighted"]
        d["family"] = "DL"
        frames.append(d)
    fnd = DL_TABLES / "foundation_models.xlsx"
    if fnd.exists():
        d = pd.read_excel(fnd, sheet_name="pooled")
        d = d[d["selection"] == "zero_shot"]
        d["family"] = "Foundation"
        frames.append(d)

    board = pd.concat(frames, ignore_index=True)
    board = board[(board["split"] == "test")
                  & (board["protocol"] == PROTOCOL)
                  & (~board["model"].str.startswith("Dummy"))]

    # Which of these the application can put in its menu. Every family is
    # servable, so the column is normally all "yes"; it exists because the
    # benchmark also contains configurations that were scored and not
    # exported, and a reader comparing the table against the menu should not
    # have to guess which those are.
    served = served_pairs()
    board["served"] = [(m, t) in served
                       for m, t in zip(board["model"], board["task"])]

    tables, full = {}, {}
    for task in ("printability", "cell_response"):
        cell = (board[board["task"] == task]
                .sort_values("weighted_f1", ascending=False))
        cols = ["model", "family", "served", "accuracy", "weighted_f1",
                "macro_f1", "mcc", "roc_auc_weighted_ovr"]
        head = ["Model", "Type", "In menu", "Accuracy", "Weighted F1",
                "Macro F1", "MCC", "ROC-AUC"]

        def to_md(frame):
            out = ["| " + " | ".join(head) + " |",
                   "|" + "|".join(["---"] * len(head)) + "|"]
            for r in frame[cols].itertuples(index=False):
                vals = [str(r[0]), str(r[1]), "yes" if r[2] else "-"] + [
                    "n/a" if pd.isna(v) else f"{v:.3f}" for v in r[3:]]
                out.append("| " + " | ".join(vals) + " |")
            return "\n".join(out)

        tables[task] = to_md(cell.head(TOP_N))
        full[task] = to_md(cell)

    body = _header("Benchmarked test-set performance shown in the interface.")
    body += (f"# Random-split hold-out, test partition, weighted-F1 selection.\n"
             f"# n = 530 test records for both targets.\n\n")
    body += f"PERFORMANCE_PROTOCOL = {PROTOCOL!r}\n\n"
    body += "PERFORMANCE_GUIDE = {\n"
    for k, v in tables.items():
        body += f'    {k!r}: """\n{v}\n""",\n'
    body += "}\n\nPERFORMANCE_GUIDE_FULL = {\n"
    for k, v in full.items():
        body += f'    {k!r}: """\n{v}\n""",\n'
    body += "}\n"
    (HERE / "model_performance.py").write_text(body, encoding="utf-8")
    print(f"  model_performance.py  {len(board)} scored model-task rows "
          f"({PROTOCOL} split, test partition)")


def build_corpus_reference(df, columns) -> None:
    """
    The formulations themselves, trimmed to what grounding and range checks need.

    Column groups are written beside the table because `nearest_formulations`
    and `distance_report` need to know which columns are biomaterials, which are
    printing parameters and which are targets, and the application has no
    dataset loader to ask.
    """
    keep = [c for c in (list(columns.biomaterials) + list(cfg.CELL_COLS)
                        + list(columns.print_params) + list(cfg.TARGETS))
            if c in df.columns]
    df[keep].to_parquet(HERE / "corpus_reference.parquet", index=False)

    groups = {"biomaterials": [c for c in columns.biomaterials if c in keep],
              "print_params": [c for c in columns.print_params if c in keep],
              "predictors": [c for c in columns.predictors if c in keep],
              "targets": [c for c in cfg.TARGETS if c in keep],
              "n_records": int(len(df))}
    (HERE / "corpus_reference.json").write_text(
        json.dumps(groups, indent=1), encoding="utf-8")

    kb = (HERE / "corpus_reference.parquet").stat().st_size / 1024
    print(f"  corpus_reference      {len(df)} rows x {len(keep)} columns "
          f"({kb:.0f} KB)")


def main() -> None:
    df, columns = load_dataset()
    print(f"dataset {df.shape[0]} rows")
    build_biomaterials(df, columns)
    build_cell_lines(df, columns)
    build_performance()
    build_corpus_reference(df, columns)
    print(f"\n-> {HERE}")


if __name__ == "__main__":
    main()
