"""
Cell-line vocabulary and observed seeding densities.

GENERATED by 06_webapp/build_app_data.py - do not edit by hand.
Regenerate after any change to the dataset or the benchmark tables.
"""

# Ordered by frequency in the corpus, with the acellular token
# first because it selects a different mode: cell response is
# not applicable and WSSQ falls back to printability alone.
ACELLULAR_TOKEN = 'NoCellCultured'

CELL_LINE_OPTIONS = [
    'NoCellCultured',
    'HUVECs',
    'HepG2',
    'bMSCs',
    'chondrocytes',
    'NIH3T3',
    'HepaRG',
    'hiPSC-CMs /ATCCs',
    'Myoblast cells',
    'H9c2',
    'HEK',
    'CPCs',
    'MESCs',
    'hiPSCs',
    'L929',
    'Primary mouse hepatocyte',
    'NSCLC PDX',
    'human primary kidney cells',
    'Cardiac progenitor cells',
    '10T1/2',
    'HAVIC',
    'RAMECs',
    'hESCs',
    'human nasoseptal chondrocytes',
    'PDX',
    'PTECs',
    'HPFs',
    'MG-63',
    'dermal fibroblasts',
    'HASSMC',
    'Saos-2',
    'MC3T3-E1',
    'hASCs',
    'SU3',
    'ESCs',
    'RPTEC/TERT1',
    'hiPSC-CMs and HS-27A',
    'HADMSCs',
    'HACs',
    'MRC5',
    'HeLa',
    'RHECs',
    'cardiomyocytes',
    'human adipogenic mesenchymal stem cells',
    'MSCs',
    'HUVECs/MSCs',
    'U87-MG',
    'RSC96/HUVECs',
    'HEPG2/ECs',
    'A549',
    'Human non-small cell lung cancer line Calu-3 (Calu-3)',
    'hTMSCs',
    'mouse cardiac cells',
    'Human cardiac fibroblasts',
    'Schwann cells',
    'hTERT-MSC',
    'bMSCs/hACs',
    'basil plant cell',
    'EPCs',
    'HepaRG / LX-2',
    'Caki-1',
    'human induced pluripotent stem cell-derived cardiomyocytes',
    'human epithelial lung carcinoma cells',
    'HCF',
    'Huh7',
    '3T3 Fibroblasts',
    'EA.hy 926 cells',
    'human coronary artery endothelial cells',
    'NIH3T3/ HUVECs',
    'neonatal rat ventricular CFs',
    'HepG2/C3A',
    'IMR-90',
    'rMSC',
    'hiPSC-CM / fibroblasts',
    'HUVECs/H9C2',
    'fibroblasts',
    'Endothelial cells',
    'neonatal rat ventricular cardiomyocytes',
    'Neonatal mouse cardiomyocytes (NMVCMs)',
    'murine macrophage-like cell line',
    '293FT',
    'sADSC',
    'human hepatic stellate cell line',
    'aHSC',
    'NRCMs',
    'HBE',
    'HEK-293',
    'Wnt3a-293FT',
    'Human aortic VIC',
    'HEK 293FT',
    'HNDF',
    'Huh7/HepaRG',
    'hiHeps',
    'hCPCs',
    'pancreatic islets cells',
    'ICC',
    'Wnt reporter-293FT',
    'Human CPCs',
    'human cardiac progenitor cells',
    'SMC',
    'hepatoma',
    'cardiomyocyte/MSCs',
    'FB',
    'eHep',
    'PMHs',
    'Human CM /adult human fibroblasts',
    'HUVSMCs',
    'ACPCs',
    'MC3T3',
    'hNCs',
    'primary rat hepatocyte',
    'Human umbilical vein endothelial cells',
    'HPAAF',
    'VIC',
    'HLC',
    'ADSCs',
    'MFCs',
    'A549 GFP+',
    'ATDC5',
    'CFs/CMs/HUVECs',
    'n neonatal mouse ventricular cardiomyocytes',
    'Human MSCs',
    'Human CPCs / MSCs',
    'hESC-derived HLCs',
    'HCASMCs',
    'iCMs/iCFs/iECs/iCMFs',
    'VICs',
    'iPSCs',
    'primary human hepatocytes',
    'SMCs',
    'iCMs/iCFs/iECs',
    'PC9',
    'H1395',
    'H1650',
    'HUVECs and hiPSC-CS',
    'human neonatal dermal fi broblasts',
    '10T1/2 fibroblast-laden cells',
    'iCMFs',
    'neonatal rat ventricular CMs',
    'U87',
    'NSCLC PDX/CAFs',
    'iPSC-derived CM',
    'NIH 3T3 mouse fibroblasts',
    'Neonatal rat cardiomyocytes',
    'hiPSCs-derived HLCs',
    'iPSCs/HUVECs',
    'HULEC-5a',
    'HUVECs and HHSCs',
    'NCI-H1703',
    '75% hepatoblast cells, 20% iEC and 5% iMSC',
    'Intrahepatic cholangiocarcinoma (ICC)',
    'NCI-H441',
    'Human Umbilical Vein Endothelial Cells + iPSC-derived CM',
    'rabbit bone marrow mesenchymal stem cells',
    'CMs/CFs',
    'cardiac fibroblasts',
    'iPSCs-derived cardiomyocytes',
    'cardiomyocytes/ fibroblasts',
    'hiPSC-CM',
    'iPSC-CMs',
    'hBM-MSCs',
    'Hepatoblast- single cell/iESC/iMSC',
    'Hepatoblast- spheroid/iESC/iMSC',
    'human primary parathyroid cells',
    'prostate cancer stem cell',
    'HL-1',
    'CPCs / MSCs',
    'pancreatic cancer cell',
    'A549/95-D cells',
    'SMMC-7721',
    'rat ventricular cardiomyocytes',
    'A549 lung adenocarcinoma cells',
    'HMEC-1/ fibroblast/ THP-1',
    'HMEC-1',
    'HAVSMC',
    'HUVEC/HHSC',
    'LX-2',
    'Fibroblasts/THP-1',
    'HLF',
    'HUVECs / LX-2',
    'CCAO',
    'Hepa RG/ HUVEC',
    'BEAS2B',
    'PDGFRβ+',
    'hMSCs',
    'CiPSC-HOs',
    'tubular epithelial',
]

CELL_LINE_COUNTS = {
    'NoCellCultured': 1573,
    'HUVECs': 75,
    'HepG2': 71,
    'bMSCs': 65,
    'chondrocytes': 39,
    'NIH3T3': 35,
    'HepaRG': 28,
    'hiPSC-CMs /ATCCs': 26,
    'Myoblast cells': 26,
    'H9c2': 25,
    'HEK': 24,
    'CPCs': 21,
    'MESCs': 20,
    'hiPSCs': 17,
    'L929': 15,
    'Primary mouse hepatocyte': 14,
    'NSCLC PDX': 13,
    'human primary kidney cells': 13,
    'Cardiac progenitor cells': 13,
    '10T1/2': 13,
    'HAVIC': 12,
    'RAMECs': 12,
    'hESCs': 11,
    'human nasoseptal chondrocytes': 10,
    'PDX': 10,
    'PTECs': 10,
    'HPFs': 10,
    'MG-63': 9,
    'dermal fibroblasts': 9,
    'HASSMC': 9,
    'Saos-2': 8,
    'MC3T3-E1': 8,
    'hASCs': 8,
    'SU3': 8,
    'ESCs': 8,
    'RPTEC/TERT1': 8,
    'hiPSC-CMs and HS-27A': 8,
    'HADMSCs': 7,
    'HACs': 7,
    'MRC5': 7,
    'HeLa': 7,
    'RHECs': 6,
    'cardiomyocytes': 6,
    'human adipogenic mesenchymal stem cells': 6,
    'MSCs': 6,
    'HUVECs/MSCs': 6,
    'U87-MG': 6,
    'RSC96/HUVECs': 6,
    'HEPG2/ECs': 6,
    'A549': 6,
    'Human non-small cell lung cancer line Calu-3 (Calu-3)': 5,
    'hTMSCs': 5,
    'mouse cardiac cells': 5,
    'Human cardiac fibroblasts': 5,
    'Schwann cells': 5,
    'hTERT-MSC': 4,
    'bMSCs/hACs': 4,
    'basil plant cell': 4,
    'EPCs': 4,
    'HepaRG / LX-2': 4,
    'Caki-1': 4,
    'human induced pluripotent stem cell-derived cardiomyocytes': 4,
    'human epithelial lung carcinoma cells': 4,
    'HCF': 4,
    'Huh7': 4,
    '3T3 Fibroblasts': 4,
    'EA.hy 926 cells': 4,
    'human coronary artery endothelial cells': 4,
    'NIH3T3/ HUVECs': 4,
    'neonatal rat ventricular CFs': 4,
    'HepG2/C3A': 4,
    'IMR-90': 4,
    'rMSC': 4,
    'hiPSC-CM / fibroblasts': 3,
    'HUVECs/H9C2': 3,
    'fibroblasts': 3,
    'Endothelial cells': 3,
    'neonatal rat ventricular cardiomyocytes': 3,
    'Neonatal mouse cardiomyocytes (NMVCMs)': 3,
    'murine macrophage-like cell line': 3,
    '293FT': 3,
    'sADSC': 3,
    'human hepatic stellate cell line': 3,
    'aHSC': 3,
    'NRCMs': 3,
    'HBE': 3,
    'HEK-293': 3,
    'Wnt3a-293FT': 3,
    'Human aortic VIC': 3,
    'HEK 293FT': 3,
    'HNDF': 2,
    'Huh7/HepaRG': 2,
    'hiHeps': 2,
    'hCPCs': 2,
    'pancreatic islets cells': 2,
    'ICC': 2,
    'Wnt reporter-293FT': 2,
    'Human CPCs': 2,
    'human cardiac progenitor cells': 2,
    'SMC': 2,
    'hepatoma': 2,
    'cardiomyocyte/MSCs': 2,
    'FB': 2,
    'eHep': 2,
    'PMHs': 2,
    'Human CM /adult human fibroblasts': 2,
    'HUVSMCs': 2,
    'ACPCs': 2,
    'MC3T3': 2,
    'hNCs': 2,
    'primary rat hepatocyte': 2,
    'Human umbilical vein endothelial cells': 2,
    'HPAAF': 2,
    'VIC': 2,
    'HLC': 2,
    'ADSCs': 2,
    'MFCs': 2,
    'A549 GFP+': 2,
    'ATDC5': 2,
    'CFs/CMs/HUVECs': 2,
    'n neonatal mouse ventricular cardiomyocytes': 2,
    'Human MSCs': 2,
    'Human CPCs / MSCs': 2,
    'hESC-derived HLCs': 2,
    'HCASMCs': 2,
    'iCMs/iCFs/iECs/iCMFs': 1,
    'VICs': 1,
    'iPSCs': 1,
    'primary human hepatocytes': 1,
    'SMCs': 1,
    'iCMs/iCFs/iECs': 1,
    'PC9': 1,
    'H1395': 1,
    'H1650': 1,
    'HUVECs and hiPSC-CS': 1,
    'human neonatal dermal fi broblasts': 1,
    '10T1/2 fibroblast-laden cells': 1,
    'iCMFs': 1,
    'neonatal rat ventricular CMs': 1,
    'U87': 1,
    'NSCLC PDX/CAFs': 1,
    'iPSC-derived CM': 1,
    'NIH 3T3 mouse fibroblasts': 1,
    'Neonatal rat cardiomyocytes': 1,
    'hiPSCs-derived HLCs': 1,
    'iPSCs/HUVECs': 1,
    'HULEC-5a': 1,
    'HUVECs and HHSCs': 1,
    'NCI-H1703': 1,
    '75% hepatoblast cells, 20% iEC and 5% iMSC': 1,
    'Intrahepatic cholangiocarcinoma (ICC)': 1,
    'NCI-H441': 1,
    'Human Umbilical Vein Endothelial Cells + iPSC-derived CM': 1,
    'rabbit bone marrow mesenchymal stem cells': 1,
    'CMs/CFs': 1,
    'cardiac fibroblasts': 1,
    'iPSCs-derived cardiomyocytes': 1,
    'cardiomyocytes/ fibroblasts': 1,
    'hiPSC-CM': 1,
    'iPSC-CMs': 1,
    'hBM-MSCs': 1,
    'Hepatoblast- single cell/iESC/iMSC': 1,
    'Hepatoblast- spheroid/iESC/iMSC': 1,
    'human primary parathyroid cells': 1,
    'prostate cancer stem cell': 1,
    'HL-1': 1,
    'CPCs / MSCs': 1,
    'pancreatic cancer cell': 1,
    'A549/95-D cells': 1,
    'SMMC-7721': 1,
    'rat ventricular cardiomyocytes': 1,
    'A549 lung adenocarcinoma cells': 1,
    'HMEC-1/ fibroblast/ THP-1': 1,
    'HMEC-1': 1,
    'HAVSMC': 1,
    'HUVEC/HHSC': 1,
    'LX-2': 1,
    'Fibroblasts/THP-1': 1,
    'HLF': 1,
    'HUVECs / LX-2': 1,
    'CCAO': 1,
    'Hepa RG/ HUVEC': 1,
    'BEAS2B': 1,
    'PDGFRβ+': 1,
    'hMSCs': 1,
    'CiPSC-HOs': 1,
    'tubular epithelial': 1,
}

# Density in 10^6 cells/mL, among records using that line.
CELL_DENSITY_RANGES = {
    "NoCellCultured": {
        "min": 1.0,
        "max": 3.0,
        "median": 1.0
    },
    "HUVECs": {
        "min": 0.035,
        "max": 20.0,
        "median": 5.0
    },
    "HepG2": {
        "min": 1.0,
        "max": 20.0,
        "median": 1.5
    },
    "bMSCs": {
        "min": 0.25,
        "max": 20.0,
        "median": 10.0
    },
    "chondrocytes": {
        "min": 0.1,
        "max": 6.0,
        "median": 6.0
    },
    "NIH3T3": {
        "min": 0.1,
        "max": 5.0,
        "median": 2.5
    },
    "HepaRG": {
        "min": 1.0,
        "max": 20.0,
        "median": 4.0
    },
    "hiPSC-CMs /ATCCs": {
        "min": 2.0,
        "max": 2.0,
        "median": 2.0
    },
    "Myoblast cells": {
        "min": 0.366,
        "max": 10.0,
        "median": 1.0
    },
    "H9c2": {
        "min": 0.04,
        "max": 1.0,
        "median": 1.0
    },
    "HEK": {
        "min": 3.0,
        "max": 3.0,
        "median": 3.0
    },
    "CPCs": {
        "min": 2.0,
        "max": 8.0,
        "median": 2.0
    },
    "MESCs": {
        "min": 0.5,
        "max": 2.0,
        "median": 1.0
    },
    "hiPSCs": {
        "min": 1.0,
        "max": 15.0,
        "median": 15.0
    },
    "L929": {
        "min": 0.1,
        "max": 10.0,
        "median": 1.0
    },
    "Primary mouse hepatocyte": {
        "min": 0.128,
        "max": 1.0,
        "median": 0.128
    },
    "NSCLC PDX": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "human primary kidney cells": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "Cardiac progenitor cells": {
        "min": 5.0,
        "max": 5.0,
        "median": 5.0
    },
    "10T1/2": {
        "min": 0.5,
        "max": 2.0,
        "median": 0.5
    },
    "HAVIC": {
        "min": 2.5,
        "max": 10.0,
        "median": 3.75
    },
    "RAMECs": {
        "min": 1.0,
        "max": 1.0,
        "median": 1.0
    },
    "hESCs": {
        "min": 1.0,
        "max": 1.0,
        "median": 1.0
    },
    "human nasoseptal chondrocytes": {
        "min": 4.0,
        "max": 4.0,
        "median": 4.0
    },
    "PDX": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "PTECs": {
        "min": 15.0,
        "max": 15.0,
        "median": 15.0
    },
    "HPFs": {
        "min": 2.0,
        "max": 2.0,
        "median": 2.0
    },
    "MG-63": {
        "min": 0.005,
        "max": 5.0,
        "median": 0.005
    },
    "dermal fibroblasts": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "HASSMC": {
        "min": 2.5,
        "max": 2.5,
        "median": 2.5
    },
    "Saos-2": {
        "min": 5.0,
        "max": 5.0,
        "median": 5.0
    },
    "MC3T3-E1": {
        "min": 30.0,
        "max": 30.0,
        "median": 30.0
    },
    "hASCs": {
        "min": 1.0,
        "max": 2.0,
        "median": 1.3
    },
    "SU3": {
        "min": 5.0,
        "max": 5.0,
        "median": 5.0
    },
    "ESCs": {
        "min": 6.0,
        "max": 10.0,
        "median": 8.0
    },
    "RPTEC/TERT1": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "hiPSC-CMs and HS-27A": {
        "min": 20.0,
        "max": 20.0,
        "median": 20.0
    },
    "HADMSCs": {
        "min": 2.0,
        "max": 2.5,
        "median": 2.5
    },
    "HACs": {
        "min": 5.0,
        "max": 15.0,
        "median": 5.0
    },
    "MRC5": {
        "min": 0.04,
        "max": 5.0,
        "median": 3.0
    },
    "HeLa": {
        "min": 1.0,
        "max": 150.0,
        "median": 1.0
    },
    "RHECs": {
        "min": 0.5,
        "max": 0.5,
        "median": 0.5
    },
    "cardiomyocytes": {
        "min": 0.2,
        "max": 10.0,
        "median": 6.0
    },
    "human adipogenic mesenchymal stem cells": {
        "min": 0.75,
        "max": 2.25,
        "median": 1.125
    },
    "MSCs": {
        "min": 0.2,
        "max": 5.0,
        "median": 1.0
    },
    "HUVECs/MSCs": {
        "min": 6.0,
        "max": 6.0,
        "median": 6.0
    },
    "U87-MG": {
        "min": 5.25,
        "max": 5.25,
        "median": 5.25
    },
    "RSC96/HUVECs": {
        "min": 1.0,
        "max": 1.0,
        "median": 1.0
    },
    "HEPG2/ECs": {
        "min": 6.0,
        "max": 6.0,
        "median": 6.0
    },
    "A549": {
        "min": 1.0,
        "max": 5.0,
        "median": 2.5
    },
    "Human non-small cell lung cancer line Calu-3 (Calu-3)": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "hTMSCs": {
        "min": 3.5,
        "max": 3.5,
        "median": 3.5
    },
    "mouse cardiac cells": {
        "min": 0.32,
        "max": 0.32,
        "median": 0.32
    },
    "Human cardiac fibroblasts": {
        "min": 1.0,
        "max": 1.0,
        "median": 1.0
    },
    "Schwann cells": {
        "min": 1.0,
        "max": 2.0,
        "median": 1.0
    },
    "hTERT-MSC": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "bMSCs/hACs": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "EPCs": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "HepaRG / LX-2": {
        "min": 1.5,
        "max": 3.0,
        "median": 3.0
    },
    "Caki-1": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "human induced pluripotent stem cell-derived cardiomyocytes": {
        "min": 20.0,
        "max": 20.0,
        "median": 20.0
    },
    "human epithelial lung carcinoma cells": {
        "min": 7.0,
        "max": 7.0,
        "median": 7.0
    },
    "HCF": {
        "min": 2.0,
        "max": 2.0,
        "median": 2.0
    },
    "Huh7": {
        "min": 0.5,
        "max": 0.5,
        "median": 0.5
    },
    "3T3 Fibroblasts": {
        "min": 5.0,
        "max": 5.0,
        "median": 5.0
    },
    "EA.hy 926 cells": {
        "min": 5.0,
        "max": 5.0,
        "median": 5.0
    },
    "human coronary artery endothelial cells": {
        "min": 0.8,
        "max": 1.0,
        "median": 0.8
    },
    "NIH3T3/ HUVECs": {
        "min": 1.0,
        "max": 1.0,
        "median": 1.0
    },
    "neonatal rat ventricular CFs": {
        "min": 5.0,
        "max": 5.0,
        "median": 5.0
    },
    "HepG2/C3A": {
        "min": 5.0,
        "max": 5.0,
        "median": 5.0
    },
    "IMR-90": {
        "min": 3.5,
        "max": 3.5,
        "median": 3.5
    },
    "rMSC": {
        "min": 3.5,
        "max": 3.5,
        "median": 3.5
    },
    "hiPSC-CM / fibroblasts": {
        "min": 1.0,
        "max": 1.0,
        "median": 1.0
    },
    "HUVECs/H9C2": {
        "min": 4.0,
        "max": 4.0,
        "median": 4.0
    },
    "fibroblasts": {
        "min": 1.0,
        "max": 10.0,
        "median": 3.0
    },
    "neonatal rat ventricular cardiomyocytes": {
        "min": 1.0,
        "max": 200.0,
        "median": 1.0
    },
    "Neonatal mouse cardiomyocytes (NMVCMs)": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "murine macrophage-like cell line": {
        "min": 1.0,
        "max": 1.0,
        "median": 1.0
    },
    "293FT": {
        "min": 2.0,
        "max": 2.0,
        "median": 2.0
    },
    "sADSC": {
        "min": 1.0,
        "max": 3.0,
        "median": 2.0
    },
    "human hepatic stellate cell line": {
        "min": 3.0,
        "max": 5.0,
        "median": 4.0
    },
    "aHSC": {
        "min": 3.0,
        "max": 5.0,
        "median": 4.0
    },
    "NRCMs": {
        "min": 20.0,
        "max": 20.0,
        "median": 20.0
    },
    "HBE": {
        "min": 0.13,
        "max": 0.13,
        "median": 0.13
    },
    "HEK-293": {
        "min": 0.05,
        "max": 2.0,
        "median": 2.0
    },
    "Wnt3a-293FT": {
        "min": 2.0,
        "max": 2.0,
        "median": 2.0
    },
    "Human aortic VIC": {
        "min": 5.0,
        "max": 5.0,
        "median": 5.0
    },
    "HEK 293FT": {
        "min": 2.0,
        "max": 2.0,
        "median": 2.0
    },
    "HNDF": {
        "min": 2.0,
        "max": 2.0,
        "median": 2.0
    },
    "Huh7/HepaRG": {
        "min": 1.5,
        "max": 1.5,
        "median": 1.5
    },
    "hiHeps": {
        "min": 10.0,
        "max": 50.0,
        "median": 30.0
    },
    "hCPCs": {
        "min": 3.0,
        "max": 3.0,
        "median": 3.0
    },
    "pancreatic islets cells": {
        "min": 0.045,
        "max": 0.045,
        "median": 0.045
    },
    "ICC": {
        "min": 3.0,
        "max": 6.0,
        "median": 4.5
    },
    "Wnt reporter-293FT": {
        "min": 2.0,
        "max": 2.0,
        "median": 2.0
    },
    "Human CPCs": {
        "min": 5e-06,
        "max": 5.0,
        "median": 2.5000025
    },
    "human cardiac progenitor cells": {
        "min": 3.0,
        "max": 3.0,
        "median": 3.0
    },
    "SMC": {
        "min": 2.0,
        "max": 10.0,
        "median": 6.0
    },
    "hepatoma": {
        "min": 1.0,
        "max": 1.0,
        "median": 1.0
    },
    "cardiomyocyte/MSCs": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "FB": {
        "min": 1.0,
        "max": 1.0,
        "median": 1.0
    },
    "eHep": {
        "min": 5.0,
        "max": 5.0,
        "median": 5.0
    },
    "PMHs": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "Human CM /adult human fibroblasts": {
        "min": 0.01,
        "max": 0.2,
        "median": 0.10500000000000001
    },
    "HUVSMCs": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "ACPCs": {
        "min": 20.0,
        "max": 20.0,
        "median": 20.0
    },
    "MC3T3": {
        "min": 0.25,
        "max": 0.25,
        "median": 0.25
    },
    "hNCs": {
        "min": 1.0,
        "max": 15.0,
        "median": 8.0
    },
    "primary rat hepatocyte": {
        "min": 1.0,
        "max": 5.0,
        "median": 3.0
    },
    "Human umbilical vein endothelial cells": {
        "min": 1.25,
        "max": 10.0,
        "median": 5.625
    },
    "HPAAF": {
        "min": 0.4,
        "max": 4.0,
        "median": 2.2
    },
    "VIC": {
        "min": 2.0,
        "max": 10.0,
        "median": 6.0
    },
    "HLC": {
        "min": 2.0,
        "max": 2.0,
        "median": 2.0
    },
    "ADSCs": {
        "min": 2.0,
        "max": 2.0,
        "median": 2.0
    },
    "MFCs": {
        "min": 5.0,
        "max": 5.0,
        "median": 5.0
    },
    "A549 GFP+": {
        "min": 1.5,
        "max": 1.5,
        "median": 1.5
    },
    "ATDC5": {
        "min": 5.68,
        "max": 5.68,
        "median": 5.68
    },
    "CFs/CMs/HUVECs": {
        "min": 30.0,
        "max": 30.0,
        "median": 30.0
    },
    "n neonatal mouse ventricular cardiomyocytes": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "Human MSCs": {
        "min": 5e-06,
        "max": 5.0,
        "median": 2.5000025
    },
    "Human CPCs / MSCs": {
        "min": 5.0,
        "max": 5.0,
        "median": 5.0
    },
    "hESC-derived HLCs": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "HCASMCs": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "iCMs/iCFs/iECs/iCMFs": {
        "min": 3.87,
        "max": 3.87,
        "median": 3.87
    },
    "VICs": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "iPSCs": {
        "min": 8.0,
        "max": 8.0,
        "median": 8.0
    },
    "primary human hepatocytes": {
        "min": 5.0,
        "max": 5.0,
        "median": 5.0
    },
    "SMCs": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "iCMs/iCFs/iECs": {
        "min": 9.6,
        "max": 9.6,
        "median": 9.6
    },
    "PC9": {
        "min": 1.0,
        "max": 1.0,
        "median": 1.0
    },
    "H1395": {
        "min": 1.0,
        "max": 1.0,
        "median": 1.0
    },
    "H1650": {
        "min": 1.0,
        "max": 1.0,
        "median": 1.0
    },
    "HUVECs and hiPSC-CS": {
        "min": 0.01,
        "max": 0.01,
        "median": 0.01
    },
    "human neonatal dermal fi broblasts": {
        "min": 2.0,
        "max": 2.0,
        "median": 2.0
    },
    "10T1/2 fibroblast-laden cells": {
        "min": 2.0,
        "max": 2.0,
        "median": 2.0
    },
    "iCMFs": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "neonatal rat ventricular CMs": {
        "min": 5.0,
        "max": 5.0,
        "median": 5.0
    },
    "U87": {
        "min": 5.0,
        "max": 5.0,
        "median": 5.0
    },
    "NSCLC PDX/CAFs": {
        "min": 5.0,
        "max": 5.0,
        "median": 5.0
    },
    "iPSC-derived CM": {
        "min": 8.0,
        "max": 8.0,
        "median": 8.0
    },
    "NIH 3T3 mouse fibroblasts": {
        "min": 5.0,
        "max": 5.0,
        "median": 5.0
    },
    "Neonatal rat cardiomyocytes": {
        "min": 0.2,
        "max": 0.2,
        "median": 0.2
    },
    "hiPSCs-derived HLCs": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "iPSCs/HUVECs": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "HULEC-5a": {
        "min": 6.0,
        "max": 6.0,
        "median": 6.0
    },
    "HUVECs and HHSCs": {
        "min": 1.8,
        "max": 1.8,
        "median": 1.8
    },
    "NCI-H1703": {
        "min": 6.0,
        "max": 6.0,
        "median": 6.0
    },
    "75% hepatoblast cells, 20% iEC and 5% iMSC": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "Intrahepatic cholangiocarcinoma (ICC)": {
        "min": 1.0,
        "max": 1.0,
        "median": 1.0
    },
    "NCI-H441": {
        "min": 6.0,
        "max": 6.0,
        "median": 6.0
    },
    "Human Umbilical Vein Endothelial Cells + iPSC-derived CM": {
        "min": 6.0,
        "max": 6.0,
        "median": 6.0
    },
    "rabbit bone marrow mesenchymal stem cells": {
        "min": 0.1,
        "max": 0.1,
        "median": 0.1
    },
    "CMs/CFs": {
        "min": 30.0,
        "max": 30.0,
        "median": 30.0
    },
    "cardiac fibroblasts": {
        "min": 5.0,
        "max": 5.0,
        "median": 5.0
    },
    "iPSCs-derived cardiomyocytes": {
        "min": 200.0,
        "max": 200.0,
        "median": 200.0
    },
    "cardiomyocytes/ fibroblasts": {
        "min": 0.2,
        "max": 0.2,
        "median": 0.2
    },
    "hiPSC-CM": {
        "min": 0.2,
        "max": 0.2,
        "median": 0.2
    },
    "iPSC-CMs": {
        "min": 4.0,
        "max": 4.0,
        "median": 4.0
    },
    "hBM-MSCs": {
        "min": 0.25,
        "max": 0.25,
        "median": 0.25
    },
    "Hepatoblast- single cell/iESC/iMSC": {
        "min": 5.6,
        "max": 5.6,
        "median": 5.6
    },
    "Hepatoblast- spheroid/iESC/iMSC": {
        "min": 5.6,
        "max": 5.6,
        "median": 5.6
    },
    "human primary parathyroid cells": {
        "min": 0.06,
        "max": 0.06,
        "median": 0.06
    },
    "prostate cancer stem cell": {
        "min": 2.0,
        "max": 2.0,
        "median": 2.0
    },
    "HL-1": {
        "min": 8.0,
        "max": 8.0,
        "median": 8.0
    },
    "CPCs / MSCs": {
        "min": 5.0,
        "max": 5.0,
        "median": 5.0
    },
    "pancreatic cancer cell": {
        "min": 2.0,
        "max": 2.0,
        "median": 2.0
    },
    "A549/95-D cells": {
        "min": 1.0,
        "max": 1.0,
        "median": 1.0
    },
    "SMMC-7721": {
        "min": 0.5,
        "max": 0.5,
        "median": 0.5
    },
    "rat ventricular cardiomyocytes": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "A549 lung adenocarcinoma cells": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "HMEC-1/ fibroblast/ THP-1": {
        "min": 35.0,
        "max": 35.0,
        "median": 35.0
    },
    "HMEC-1": {
        "min": 25.0,
        "max": 25.0,
        "median": 25.0
    },
    "HAVSMC": {
        "min": 1.5,
        "max": 1.5,
        "median": 1.5
    },
    "HUVEC/HHSC": {
        "min": 0.9,
        "max": 0.9,
        "median": 0.9
    },
    "LX-2": {
        "min": 0.5,
        "max": 0.5,
        "median": 0.5
    },
    "Fibroblasts/THP-1": {
        "min": 14.25,
        "max": 14.25,
        "median": 14.25
    },
    "HLF": {
        "min": 5.0,
        "max": 5.0,
        "median": 5.0
    },
    "HUVECs / LX-2": {
        "min": 10.0,
        "max": 10.0,
        "median": 10.0
    },
    "CCAO": {
        "min": 0.02,
        "max": 0.02,
        "median": 0.02
    },
    "Hepa RG/ HUVEC": {
        "min": 20.0,
        "max": 20.0,
        "median": 20.0
    },
    "BEAS2B": {
        "min": 2.0,
        "max": 2.0,
        "median": 2.0
    },
    "PDGFR\u03b2+": {
        "min": 0.25,
        "max": 0.25,
        "median": 0.25
    },
    "hMSCs": {
        "min": 2.0,
        "max": 2.0,
        "median": 2.0
    },
    "CiPSC-HOs": {
        "min": 2.5,
        "max": 2.5,
        "median": 2.5
    },
    "tubular epithelial": {
        "min": 0.4,
        "max": 0.4,
        "median": 0.4
    }
}
