"""
Assemble and publish the Hugging Face Space
===========================================

    python 06_webapp/build_app_data.py          # first, if the data changed
    python 06_webapp/deploy_to_hf.py            # stage and check, no upload
    python 06_webapp/deploy_to_hf.py --push     # stage, check and upload

Builds a self-contained copy of the application under `deploy/space/` and,
with `--push`, uploads it to the Space. Staging rather than uploading the
repository directly, because the two trees are not the same shape: the Space
needs `app.py` at its root, the serving subset of the model artefacts and none
of the analysis stages, and a requirements file that omits everything used only
for training.

The staged tree mirrors the repository layout below its own root, so
`mlate.config.ROOT` resolves the same way in both and no path in the package
needs to know where it is running:

    app.py                    from 06_webapp/app.py
    biomaterials.py           generated by build_app_data.py
    cell_lines.py                     "
    model_performance.py              "
    corpus_reference.parquet          "
    corpus_reference.json             "
    requirements.txt          serving environment
    README.md                 Space configuration
    mlate/                    the package
    deploy/models/            preprocessors, and the artefacts actually served

Study-grouped artefacts are not uploaded. The application serves the random
split, so shipping the grouped copies would double the image for files no menu
can reach; they remain in the repository and in the manuscript.

The token is never handled here. `huggingface_hub` reads it from the login
performed with `hf auth login`, or from HF_TOKEN in the environment.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import tempfile
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from mlate import config as cfg

HERE = Path(__file__).resolve().parent
STAGE = cfg.DEPLOY_DIR / "space"
REPO_ID = "Saeed/MLATE"

# Written by build_app_data.py, and required at run time: the vocabularies, the
# benchmark tables, and the trimmed corpus the prompt is grounded in.
GENERATED = ["biomaterials.py", "cell_lines.py", "model_performance.py",
             "corpus_reference.parquet", "corpus_reference.json"]

# The whole package is copied, not the six modules the application imports.
# Walking the import graph says six are enough and the import graph is wrong:
# the fitted preprocessor is a pickle holding instances of the custom imputers,
# which pickle stores by reference, so unpickling it imports `mlate.imputation`
# even though no line of the application mentions it. Trimming the package
# passed every static check and then failed on the first prediction with
# `ModuleNotFoundError: No module named 'mlate.imputation'`. The whole package
# is 576 KB against 80 MB of artefacts, so there is nothing to win here.

# Served model artefacts. The foundation models carry no split protocol and the
# preprocessor is shared, so both are copied whole.
MODEL_SUBDIRS = ["preprocessors", "foundation",
                 "classifiers/random", "deep/random"]


def stage() -> Path:
    """Build the Space tree from scratch and return its root."""
    if STAGE.exists():
        shutil.rmtree(STAGE)
    STAGE.mkdir(parents=True)

    shutil.copy2(HERE / "app.py", STAGE / "app.py")
    shutil.copy2(HERE / "requirements.txt", STAGE / "requirements.txt")
    shutil.copy2(HERE / "README.md", STAGE / "README.md")

    missing = [name for name in GENERATED if not (HERE / name).exists()]
    if missing:
        raise SystemExit(
            f"missing generated files: {', '.join(missing)}\n"
            f"run `python 06_webapp/build_app_data.py` first")
    for name in GENERATED:
        shutil.copy2(HERE / name, STAGE / name)

    shutil.copytree(cfg.ROOT / "mlate", STAGE / "mlate",
                    ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))

    models = STAGE / "deploy" / "models"
    models.mkdir(parents=True)
    shutil.copy2(cfg.MODEL_DIR / "deployment_manifest.json",
                 models / "deployment_manifest.json")
    for sub in MODEL_SUBDIRS:
        src = cfg.MODEL_DIR / sub
        if not src.exists():
            raise SystemExit(f"missing artefacts: {src}\n"
                             f"run `python 06_webapp/export_deployment.py`")
        shutil.copytree(src, models / sub)

    (STAGE / ".gitattributes").write_text(
        # Hugging Face stores these through LFS. Declared even though every
        # artefact is currently under the 10 MB threshold, because the limit is
        # a property of the file and a future model may cross it.
        "*.pkl filter=lfs diff=lfs merge=lfs -text\n"
        "*.pt filter=lfs diff=lfs merge=lfs -text\n"
        "*.parquet filter=lfs diff=lfs merge=lfs -text\n",
        encoding="utf-8")
    return STAGE


def check(root: Path) -> None:
    """
    Import and start the staged copy, not the repository copy.

    A Space failing on its first build is slow to diagnose and slower to fix,
    and every failure worth catching here is a missing file rather than a
    logical error: the tree is assembled by hand, so the way it breaks is that
    something was not copied into it.
    """
    probe = "\n".join([
        "import sys, pathlib",
        "root = pathlib.Path(sys.argv[1])",
        "sys.path.insert(0, str(root))",
        "import numpy as np, pandas as pd",
        "import mlate.config as cfg",
        "assert cfg.ROOT == root, (cfg.ROOT, root)",
        "from mlate import serving",
        "import biomaterials, cell_lines, model_performance",
        "import joblib",
        # Loading the preprocessor is the step that catches a module the
        # application never imports but a pickle needs by reference.
        "pre = joblib.load(cfg.PREPROCESSOR_DIR / 'preprocessor.pkl')",
        "cols = joblib.load(cfg.PREPROCESSOR_DIR / 'input_columns.pkl')",
        "row = pd.DataFrame([{c: 0.0 for c in cols}])",
        "row[cfg.CELL_COLS[0]] = 'bMSCs'",
        "X = np.asarray(pre.transform(row[cols]), dtype=float)",
        "print(f'  preprocessor: {X.shape[1]} features')",
        "for task in ('printability', 'cell_response'):",
        "    stubs = serving.discover(cfg.MODEL_DIR, task, 'random')",
        "    assert stubs, task",
        "    seen = {}",
        "    for stub in stubs:",
        "        seen.setdefault(stub.family, stub)",
        # One model of each family, actually opened and actually run. The
        # earlier version of this check only listed filenames, which is why a
        # broken package trim reached a running application.
        "    for family, stub in sorted(seen.items()):",
        "        proba = stub.open().predict_proba(X)",
        "        assert proba.shape[0] == 1, proba.shape",
        "        print(f'  {task}/{family}: {stub.name} -> {proba.shape[1]} classes')",
        "    print(f'  {task}: {len(stubs)} models, best {stubs[0].name}')",
        "n = len(pd.read_parquet(root / 'corpus_reference.parquet'))",
        "print(f'  corpus reference: {n} rows')",
    ])

    print("checking the staged tree")
    # Run from a scratch directory, not from the tree being checked. Loading a
    # foundation model makes its library fetch a checkpoint, and TabPFN writes
    # that 42 MB file into the working directory: checking in place left the
    # checkpoint sitting in the tree, ready to be uploaded to the Space.
    # `mlate.config.ROOT` is derived from the package location, not the working
    # directory, so nothing here depends on where the probe runs.
    with tempfile.TemporaryDirectory() as scratch:
        out = subprocess.run([sys.executable, "-c", probe, str(root)],
                             capture_output=True, text=True, cwd=scratch)
    if out.returncode:
        raise SystemExit(f"the staged tree does not import:\n{out.stderr}")
    print(out.stdout.rstrip())



def clean(root: Path) -> int:
    """
    Remove anything that appeared in the tree after it was assembled.

    Byte-compiled caches, and any checkpoint a model library decided to fetch.
    Uploading either would put megabytes into the Space that its own build
    regenerates or re-downloads on first use anyway.
    """
    removed = 0
    for path in list(root.rglob("__pycache__")) + list(root.rglob(".cache")):
        if path.is_dir():
            shutil.rmtree(path, ignore_errors=True)
            removed += 1
    for path in list(root.rglob("*.ckpt")) + list(root.rglob("*.pyc")):
        if path.is_file():
            path.unlink()
            removed += 1
    return removed

def size(root: Path) -> tuple[int, int]:
    files = [p for p in root.rglob("*") if p.is_file()]
    return len(files), sum(p.stat().st_size for p in files)


def push(root: Path, repo_id: str, message: str) -> None:
    from huggingface_hub import HfApi, get_token

    if not get_token():
        raise SystemExit(
            "No Hugging Face token. Run `hf auth login` first, or set "
            "HF_TOKEN in the environment. The token is never read or written "
            "by this script.")
    api = HfApi()
    api.upload_folder(folder_path=str(root), repo_id=repo_id,
                      repo_type="space", commit_message=message)
    print(f"\n-> https://huggingface.co/spaces/{repo_id}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--push", action="store_true",
                    help="upload the staged tree to the Space")
    ap.add_argument("--repo", default=REPO_ID)
    ap.add_argument("--message", default="Update MLATE V3 application")
    args = ap.parse_args()

    root = stage()
    check(root)
    dropped = clean(root)
    if dropped:
        print(f"  removed {dropped} item(s) the check left behind")
    n, total = size(root)
    print(f"\nstaged {n} files, {total / 2**20:.1f} MB -> {root}")

    if args.push:
        push(root, args.repo, args.message)
    else:
        print("\nnot uploaded. Re-run with --push to publish, after "
              "`hf auth login`.")


if __name__ == "__main__":
    main()
