"""
Benchmarked test-set performance shown in the interface.

GENERATED by 06_webapp/build_app_data.py - do not edit by hand.
Regenerate after any change to the dataset or the benchmark tables.
"""

# Random-split hold-out, test partition, weighted-F1 selection.
# n = 530 test records for both targets.

PERFORMANCE_PROTOCOL = 'random'

PERFORMANCE_GUIDE = {
    'printability': """
| Model | Type | In menu | Accuracy | Weighted F1 | Macro F1 | MCC | ROC-AUC |
|---|---|---|---|---|---|---|---|
| TabICL | Foundation | yes | 0.806 | 0.806 | 0.771 | 0.702 | 0.930 |
| Bagged Trees | ML | yes | 0.794 | 0.792 | 0.763 | 0.677 | 0.915 |
| CatBoost | ML | yes | 0.789 | 0.786 | 0.754 | 0.669 | 0.918 |
| Hist Gradient Boosting | ML | yes | 0.787 | 0.784 | 0.758 | 0.667 | 0.917 |
| TabPFN (thinking) | Foundation | yes | 0.779 | 0.779 | 0.738 | 0.659 | 0.918 |
| Stacking (RF+XGB+LR -> LR) | ML | yes | 0.775 | 0.773 | 0.730 | 0.649 | 0.916 |
| TabPFN | Foundation | yes | 0.770 | 0.770 | 0.719 | 0.644 | 0.918 |
| Gradient Boosting | ML | yes | 0.766 | 0.763 | 0.713 | 0.633 | 0.914 |
| LightGBM | ML | yes | 0.764 | 0.762 | 0.712 | 0.633 | 0.914 |
| XGBoost | ML | yes | 0.762 | 0.760 | 0.709 | 0.631 | 0.914 |
| Extra Trees | ML | yes | 0.760 | 0.760 | 0.713 | 0.628 | 0.910 |
| Soft Voting (RF+XGB+LR) | ML | yes | 0.760 | 0.756 | 0.703 | 0.625 | 0.900 |
""",
    'cell_response': """
| Model | Type | In menu | Accuracy | Weighted F1 | Macro F1 | MCC | ROC-AUC |
|---|---|---|---|---|---|---|---|
| Stacking (RF+XGB+LR -> LR) | ML | yes | 0.785 | 0.773 | 0.554 | 0.641 | 0.949 |
| TabPFN (thinking) | Foundation | yes | 0.774 | 0.773 | 0.555 | 0.625 | 0.960 |
| Bagged Trees | ML | yes | 0.777 | 0.773 | 0.555 | 0.629 | 0.953 |
| TabPFN | Foundation | yes | 0.781 | 0.772 | 0.534 | 0.636 | 0.958 |
| Hist Gradient Boosting | ML | yes | 0.770 | 0.767 | 0.541 | 0.617 | 0.957 |
| Random Forest (balanced) | ML | yes | 0.764 | 0.766 | 0.560 | 0.619 | 0.946 |
| TabICL | Foundation | yes | 0.770 | 0.766 | 0.546 | 0.615 | 0.959 |
| FT_Transformer | DL | yes | 0.758 | 0.754 | 0.503 | 0.600 | 0.951 |
| ResNet | DL | yes | 0.762 | 0.753 | 0.530 | 0.600 | 0.950 |
| Quadratic Discriminant | ML | yes | 0.751 | 0.749 | 0.513 | 0.586 | 0.935 |
| Soft Voting (RF+XGB+LR) | ML | yes | 0.758 | 0.744 | 0.504 | 0.591 | 0.950 |
| Bernoulli Naive Bayes | ML | yes | 0.745 | 0.743 | 0.517 | 0.577 | 0.927 |
""",
}

PERFORMANCE_GUIDE_FULL = {
    'printability': """
| Model | Type | In menu | Accuracy | Weighted F1 | Macro F1 | MCC | ROC-AUC |
|---|---|---|---|---|---|---|---|
| TabICL | Foundation | yes | 0.806 | 0.806 | 0.771 | 0.702 | 0.930 |
| Bagged Trees | ML | yes | 0.794 | 0.792 | 0.763 | 0.677 | 0.915 |
| CatBoost | ML | yes | 0.789 | 0.786 | 0.754 | 0.669 | 0.918 |
| Hist Gradient Boosting | ML | yes | 0.787 | 0.784 | 0.758 | 0.667 | 0.917 |
| TabPFN (thinking) | Foundation | yes | 0.779 | 0.779 | 0.738 | 0.659 | 0.918 |
| Stacking (RF+XGB+LR -> LR) | ML | yes | 0.775 | 0.773 | 0.730 | 0.649 | 0.916 |
| TabPFN | Foundation | yes | 0.770 | 0.770 | 0.719 | 0.644 | 0.918 |
| Gradient Boosting | ML | yes | 0.766 | 0.763 | 0.713 | 0.633 | 0.914 |
| LightGBM | ML | yes | 0.764 | 0.762 | 0.712 | 0.633 | 0.914 |
| XGBoost | ML | yes | 0.762 | 0.760 | 0.709 | 0.631 | 0.914 |
| Extra Trees | ML | yes | 0.760 | 0.760 | 0.713 | 0.628 | 0.910 |
| Soft Voting (RF+XGB+LR) | ML | yes | 0.760 | 0.756 | 0.703 | 0.625 | 0.900 |
| k-NN (distance weighted) | ML | yes | 0.749 | 0.749 | 0.714 | 0.613 | 0.850 |
| MLP (256-128) | ML | yes | 0.742 | 0.742 | 0.706 | 0.600 | 0.876 |
| ResNet | DL | yes | 0.740 | 0.741 | 0.690 | 0.604 | 0.876 |
| k-Nearest Neighbours | ML | yes | 0.736 | 0.735 | 0.707 | 0.591 | 0.797 |
| SVM (polynomial) | ML | yes | 0.730 | 0.732 | 0.670 | 0.590 | 0.881 |
| Random Forest (balanced) | ML | yes | 0.721 | 0.729 | 0.675 | 0.594 | 0.894 |
| FT_Transformer | DL | yes | 0.726 | 0.728 | 0.678 | 0.583 | 0.869 |
| TabNet_Lite | DL | yes | 0.721 | 0.721 | 0.655 | 0.573 | 0.865 |
| Decision Tree | ML | yes | 0.713 | 0.712 | 0.653 | 0.556 | 0.887 |
| NODE_Lite | DL | yes | 0.685 | 0.697 | 0.622 | 0.543 | 0.863 |
| MLP | DL | yes | 0.685 | 0.694 | 0.631 | 0.538 | 0.867 |
| SVM (RBF) | ML | yes | 0.691 | 0.691 | 0.620 | 0.529 | 0.863 |
| Logistic Regression | ML | yes | 0.672 | 0.665 | 0.574 | 0.492 | 0.829 |
| SGD (hinge) | ML | yes | 0.674 | 0.661 | 0.572 | 0.492 | n/a |
| Linear Discriminant | ML | yes | 0.675 | 0.660 | 0.559 | 0.485 | 0.834 |
| 1D_CNN | DL | yes | 0.657 | 0.654 | 0.558 | 0.479 | 0.850 |
| Passive Aggressive | ML | yes | 0.645 | 0.650 | 0.559 | 0.474 | n/a |
| Extra Tree | ML | yes | 0.658 | 0.649 | 0.556 | 0.468 | 0.863 |
| Linear SVM | ML | yes | 0.634 | 0.646 | 0.551 | 0.469 | n/a |
| Bernoulli Naive Bayes | ML | yes | 0.641 | 0.642 | 0.536 | 0.463 | 0.819 |
| Logistic Regression (balanced) | ML | yes | 0.619 | 0.636 | 0.552 | 0.460 | 0.816 |
| AdaBoost | ML | yes | 0.638 | 0.628 | 0.514 | 0.434 | 0.769 |
| Quadratic Discriminant | ML | yes | 0.619 | 0.620 | 0.513 | 0.439 | 0.816 |
| Ridge Classifier | ML | yes | 0.649 | 0.614 | 0.492 | 0.429 | n/a |
| Random Forest | ML | yes | 0.632 | 0.593 | 0.435 | 0.423 | 0.822 |
| Nearest Centroid | ML | yes | 0.464 | 0.499 | 0.404 | 0.285 | 0.810 |
| Perceptron | ML | yes | 0.536 | 0.439 | 0.320 | 0.199 | n/a |
| Gaussian Naive Bayes | ML | yes | 0.279 | 0.305 | 0.276 | 0.181 | 0.706 |
""",
    'cell_response': """
| Model | Type | In menu | Accuracy | Weighted F1 | Macro F1 | MCC | ROC-AUC |
|---|---|---|---|---|---|---|---|
| Stacking (RF+XGB+LR -> LR) | ML | yes | 0.785 | 0.773 | 0.554 | 0.641 | 0.949 |
| TabPFN (thinking) | Foundation | yes | 0.774 | 0.773 | 0.555 | 0.625 | 0.960 |
| Bagged Trees | ML | yes | 0.777 | 0.773 | 0.555 | 0.629 | 0.953 |
| TabPFN | Foundation | yes | 0.781 | 0.772 | 0.534 | 0.636 | 0.958 |
| Hist Gradient Boosting | ML | yes | 0.770 | 0.767 | 0.541 | 0.617 | 0.957 |
| Random Forest (balanced) | ML | yes | 0.764 | 0.766 | 0.560 | 0.619 | 0.946 |
| TabICL | Foundation | yes | 0.770 | 0.766 | 0.546 | 0.615 | 0.959 |
| FT_Transformer | DL | yes | 0.758 | 0.754 | 0.503 | 0.600 | 0.951 |
| ResNet | DL | yes | 0.762 | 0.753 | 0.530 | 0.600 | 0.950 |
| Quadratic Discriminant | ML | yes | 0.751 | 0.749 | 0.513 | 0.586 | 0.935 |
| Soft Voting (RF+XGB+LR) | ML | yes | 0.758 | 0.744 | 0.504 | 0.591 | 0.950 |
| Bernoulli Naive Bayes | ML | yes | 0.745 | 0.743 | 0.517 | 0.577 | 0.927 |
| Decision Tree | ML | yes | 0.747 | 0.734 | 0.479 | 0.574 | 0.935 |
| k-NN (distance weighted) | ML | yes | 0.742 | 0.734 | 0.524 | 0.565 | 0.835 |
| Extra Trees | ML | yes | 0.745 | 0.734 | 0.497 | 0.567 | 0.952 |
| CatBoost | ML | yes | 0.747 | 0.729 | 0.455 | 0.575 | 0.951 |
| Logistic Regression (balanced) | ML | yes | 0.725 | 0.729 | 0.467 | 0.550 | 0.935 |
| LightGBM | ML | yes | 0.743 | 0.727 | 0.431 | 0.570 | 0.947 |
| XGBoost | ML | yes | 0.740 | 0.724 | 0.437 | 0.563 | 0.948 |
| k-Nearest Neighbours | ML | yes | 0.730 | 0.722 | 0.495 | 0.545 | 0.820 |
| AdaBoost | ML | yes | 0.734 | 0.712 | 0.420 | 0.556 | 0.910 |
| Extra Tree | ML | yes | 0.740 | 0.712 | 0.385 | 0.564 | 0.933 |
| MLP | DL | yes | 0.723 | 0.709 | 0.447 | 0.531 | 0.933 |
| TabNet_Lite | DL | yes | 0.715 | 0.709 | 0.472 | 0.522 | 0.905 |
| Linear SVM | ML | yes | 0.721 | 0.703 | 0.453 | 0.520 | n/a |
| MLP (256-128) | ML | yes | 0.730 | 0.703 | 0.427 | 0.533 | 0.924 |
| Random Forest | ML | yes | 0.732 | 0.700 | 0.364 | 0.556 | 0.905 |
| Passive Aggressive | ML | yes | 0.715 | 0.696 | 0.435 | 0.509 | n/a |
| NODE_Lite | DL | yes | 0.719 | 0.690 | 0.421 | 0.510 | 0.926 |
| 1D_CNN | DL | yes | 0.721 | 0.689 | 0.403 | 0.517 | 0.918 |
| Linear Discriminant | ML | yes | 0.711 | 0.686 | 0.434 | 0.494 | 0.925 |
| SGD (hinge) | ML | yes | 0.717 | 0.686 | 0.406 | 0.506 | n/a |
| SVM (polynomial) | ML | yes | 0.715 | 0.685 | 0.393 | 0.506 | 0.923 |
| Logistic Regression | ML | yes | 0.715 | 0.684 | 0.405 | 0.502 | 0.925 |
| SVM (RBF) | ML | yes | 0.706 | 0.681 | 0.398 | 0.491 | 0.922 |
| Nearest Centroid | ML | yes | 0.696 | 0.679 | 0.440 | 0.499 | 0.925 |
| Gradient Boosting | ML | yes | 0.736 | 0.667 | 0.308 | 0.590 | 0.897 |
| Perceptron | ML | yes | 0.691 | 0.655 | 0.385 | 0.453 | n/a |
| Ridge Classifier | ML | yes | 0.691 | 0.648 | 0.374 | 0.447 | n/a |
| Gaussian Naive Bayes | ML | yes | 0.270 | 0.311 | 0.260 | 0.196 | 0.808 |
""",
}
